before_script:
  - echo "Execute scripts which are required to bootstrap the application. !"

after_script:
  - echo "Clean up activity can be done here !."

cache:
  paths:
    - /root/.m2/repository

stages:
  - build
  - quality
  - deploy

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - mvn clean package
  tags:
    - docker

quality:
  stage: quality
  image: maven:3.3.9-jdk-8
  script:
    - mvn sonar:sonar -Dsonar.projectKey=fr.epsi.erp -Dsonar.host.url=http://35.238.91.38 -Dsonar.login=$SONAR_TOKEN

deploy_dev:
  stage: deploy
  image: ruby:2.3
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  environment:
    name: dev
    url: https://mspr-erp-backend.herokuapp.com
  only:
    - master
  tags:
    - docker